# Rubee system file
# WARNING: DO NOT EDIT THIS FILE UNLESS YOU FEEL STRONG DESIRE
# Unpreditable behaviour may happen. Take it as your own risk.
require "bundler/setup"
Bundler.require(:default)

require "singleton"

APP_ROOT = File.expand_path(File.dirname(__FILE__))
IMAGE_DIR = File.join(APP_ROOT, 'images')

module Rubee
  class Application
    include Singleton

    def call(env)
      # autoload rb files
      Autoload.call
      # register images paths
      request = Rack::Request.new(env)
      # Add default path for images
      Router.draw { |route| route.get "/images/{path}", to: "base#image" }
      # define route
      route = Router.route_for(request)
      # init controller class
      return [404, { "content-type" => "text/plain" }, ["Route not found"]] unless route

      controller_class = "#{route[:controller].capitalize}Controller"
      # instantiate controller
      controller = Object.const_get(controller_class).new(request, route)
      # get the action
      action = route[:action]
      # fire the action
      controller.send(action)
    end
  end

  class Configuration
    include Singleton

    @configuraiton = {
      env: ENV['RACK_ENV'],
      development: {
        database_url: "",
        port: 7000
      },
      production: {},
      test: {}
    }

    class << self
      def setup(env)
        yield(self)
      end

      def database_url=(args)
        @configuraiton[args[:env].to_sym][:database_url] = args[:url]
      end

      def method_missing(method_name, *args, &block)
        if method_name.to_s.start_with?("get_")
          @configuraiton[ENV['RACK_ENV']&.to_sym || :development]&.[](method_name.to_s.delete_prefix("get_").to_sym)
        end
      end
    end
  end

  class Router
    include Singleton

    HTTP_METHODS = [:get, :post, :put, :patch, :delete, :head, :connect, :options, :trace].freeze

    attr_reader :request, :routes

    @routes = []

    class << self
      def draw
        yield(self) if block_given?
      end

      def route_for(request)
        puts request.request_method
        method = request.params["_method"] || request.request_method.downcase.to_sym
        @routes.find do |route|
          return route if request.path == route[:path] && request.request_method&.downcase&.to_sym == route[:method]

          pattern = route[:path].gsub(/{.*?}/, '([^/]+)')
          regex = %r{^#{pattern}$}
          regex.match?(request.path) && method.to_s == route[:method].to_s
        end
      end

      def set_route(path, to:, method: __method__, **args)
        controller, action = to.split("#")
        @routes.delete_if { |route| route[:path] == path && route[:method]  == method }
        @routes << { path:, controller:, action:, method:, **args }
      end

      HTTP_METHODS.each do |method|
        define_method method do |path, to:, **args|
          set_route(path, to:, method: method, **args)
        end
      end
    end
  end


  class Autoload
    class << self
      def call(black_list=[])
        # autoload all rbs
        root_directory = File.dirname(__FILE__)
        priority_order_require(root_directory, black_list)

        Dir[File.join(root_directory, '**', '*.rb')].each do |file|
          base_name = File.basename(file)

          unless base_name.end_with?('_test.rb') || (black_list + ['rubee.rb', 'test_helper.rb']).include?(base_name)
            require_relative file
          end
        end
      end

      def priority_order_require(root_directory, black_list)
        # all the base classes should be loaded first
        require_relative "config/base_configuration" unless black_list.include?('base_configuration.rb')
        require_relative "config/routes" unless black_list.include?('routes.rb')
        Dir[File.join(root_directory, 'app/models/extensions/**', '*.rb')].each do |file|
          require_relative file unless black_list.include?("#{file}.rb")
        end
        Dir[File.join(root_directory, 'app/middlewares/**', '*.rb')].each do |file|
          require_relative file unless black_list.include?("#{file}.rb")
        end
        Dir[File.join(root_directory, 'app/controllers/extensions/**', '*.rb')].each do |file|
          require_relative file unless black_list.include?("#{file}.rb")
        end
        require_relative "app/controllers/base_controller" unless black_list.include?('base_controller.rb')
        require_relative "app/models/database_object" unless black_list.include?('database_object.rb')
        require_relative "app/models/sequel_object" unless black_list.include?('sequel_object.rb')
      end
    end
  end

  class Generator
    def initialize(model_name, attributes, controller_name, action_name)
      @model_name = model_name&.downcase
      @attributes = attributes
      @plural_name = "#{controller_name.to_s.gsub("Controller", "").downcase}"
      @action_name = action_name
      @controller_name = controller_name
    end

    def call
      generate_model if @model_name
      generate_db_file if @model_name
      generate_controller if @controller_name && @action_name
      generate_view if @controller_name
    end

    private

    def generate_model
      if model_file = File.exist?("#{APP_ROOT}/app/models/#{@model_name}.rb")
        puts "Model #{@model_name} already exists. Remove it if you want to regenerate"
        return
      end

      content = <<~RUBY
        class #{@model_name.capitalize} < SequelObject
          attr_accessor #{@attributes.map { |hash| ":#{hash[:name]}"  }.join(", ")}
        end
      RUBY

      File.open("#{APP_ROOT}/app/models/#{@model_name}.rb", 'w') { |file| file.write(content) }
    end

    def generate_controller
      if controller_file = File.exist?("#{APP_ROOT}/app/controllers/#{@plural_name}_controller.rb")
        puts "Controller #{@plural_name} already exists. Remove it if you want to regenerate"
        return
      end

      content = <<~RUBY
        class #{@plural_name.capitalize}Controller < BaseController
          def #{@action_name}
            response_with
          end
        end
      RUBY

      File.open("#{APP_ROOT}/app/controllers/#{@plural_name}_controller.rb", 'w') { |file| file.write(content) }
    end

    def generate_view
      if view_file = File.exist?("#{APP_ROOT}/app/views/#{@plural_name}_#{@action_name}.erb")
        puts "View #{@plural_name}_#{@action_name} already exists. Remove it if you want to regenerate"
        return
      end

      content = <<~ERB
        <h1>#{@plural_name}_#{@action_name} View</h1>
      ERB

      File.open("#{APP_ROOT}/app/views/#{@plural_name}_#{@action_name}.erb", 'w') { |file| file.write(content) }
    end

    def generate_db_file
      if db_file = File.exist?("#{APP_ROOT}/db/create_#{@plural_name}.rb")
        puts "DB file for #{@plural_name} already exists. Remove it if you want to regenerate"
        return
      end

      content = <<~RUBY
        class Create#{@plural_name.capitalize}
          def call
          end
        end
      RUBY

      File.open("#{APP_ROOT}/db/create_#{@plural_name}.rb", 'w') { |file| file.write(content) }
    end
  end
end

