#!/usr/bin/env ruby

require 'irb'
require_relative '../../ee.rb'

ENV['RACK_ENV'] ||= 'development'

Rubee::Autoload.call

def reload
  app_files = Dir["./app/**/*.rb"]
  app_files.each { |file| load file }
  color_puts "Reloaded ..", color: :green
end

# Start IRB
IRB.start
