#!/usr/bin/env ruby
require_relative '../inits/ts/print_colors'
require_relative '../rubee.rb'
method, path = ARGV
ENV['RACK_ENV'] ||= 'development'

routes = eval(File.read('config/routes.rb'))
route = routes.find { |route| route[:path] == path.to_s && route[:method] == method.to_sym }
color_puts("Route not found with path: #{path} and method: #{method}", color: :red) unless route

Rubee::Generator.new(
  route[:model]&.[](:name),
  route[:model]&.[](:attributes),
  "#{route[:controller]&.capitalize}Controller",
  route[:action]
).call

