#!/usr/bin/env ruby

command, file_name = ARGV.first&.split(':')

if command == 'run'
  require "./db/#{file_name}.rb"
  Object.const_get(file_name.split("_").map(&:capitalize).join).new.call
else
  puts "Unknown command: #{command}"
end
