#!/usr/bin/env ruby
require_relative '../rubee.rb'
method, path = ARGV

routes = eval(File.read('config/routes.rb'))
puts routes
route = routes.find { |route| route[:path] == path.to_s && route[:method] == method.to_sym }
puts "Route not found with path: #{path} and method: #{method}" unless route

Rubee::Generator.new(
  route[:model]&.[](:name),
  route[:model]&.[](:attributes),
  "#{route[:controller]&.capitalize}Controller",
  route[:action]
).call

