#!/usr/bin/env ruby
ENV['RACK_ENV'] = 'test'
file_name = ARGV.first # Get the first argument

if file_name
  puts "Running #{file_name} test ..."
  exec("ruby -Itest -e \"require './tests/#{file_name}'\"")
else
  puts "Running all tests ..."
  exec("ruby -Itest -e \"Dir.glob('./tests/**/*_test.rb').each { |file| require file }\"")
end

