# Rubee system file
# WARNING: DO NOT EDIT THIS FILE UNLESS YOU FEEL STRONG DESIRE
# Unpreditable behaviour may happen. Take it as your own risk.
module Asyncable
  def run_async(args={})
    args.merge!(_class: self.class)
    adapter.new.run_async(**args)
  end

  def adapter
    @adapter ||= Rubee::Configuration.get_async_adapter
  end
end
