# Rubee system file
# WARNING: DO NOT EDIT THIS FILE UNLESS YOU FEEL STRONG DESIRE
# Unpreditable behaviour may happen. Take it as your own risk.

# This is very basic thread based async adapter, based on ThreadPool!!!
# Use it with cautions!
# Use cases:
# * Short-lived, non-critical tasks (e.g., logging, cache warming, async notifications).
# * Jobs that don’t require retries (e.g., analytics tracking).
# * Single-server applications where persistence is not required.
class ThreadAsync
  def run_async(**args)
    ThreadPool.instance.enqueue(args[:_class], args)
  end
end
