# Rubee system file
# WARNING: DO NOT EDIT THIS FILE UNLESS YOU FEEL STRONG DESIRE
# Unpreditable behaviour may happen. Take it as your own risk.

unless defined?(Rubee)
  require_relative '../../../../ee.rb'
  Rubee::Autoload.call
end

module Asyncable
  def perform_async(args={})
    args.merge!(_class: self.class)
    adapter.new.perform_async(**args)
  end

  def adapter
    @adapter ||= (Rubee::Configuration.get_async_adapter || ThreadAsync)
  end
end
