# Rubee system file
# WARNING: DO NOT EDIT THIS FILE UNLESS YOU FEEL STRONG DESIRE
# Unpreditable behaviour may happen. Take it as your own risk.

# This is very basic thread based async adapter, based on thread pool. \
# Queue may not be thread-safe and can be missed during the process shutdown.
# Use it with cautions!
# Use cases:
# * Short-lived, non-critical tasks (e.g., logging, cache warming, async notifications).
# * Jobs that don’t require retries (e.g., analytics tracking).
# * Single-server applications where persistence is not required.
class ThreadAsync
  def perform_async(**args)
    color_puts "WARN: ThreadAsync engine is not yet recommended for production", color: :yellow
    ThreadPool.instance.enqueue(args[:_class], args[:options])
  end
end
