# Rubee system file
# WARNING: DO NOT EDIT THIS FILE UNLESS YOU FEEL STRONG DESIRE
# Unpreditable behaviour may happen. Take it as your own risk.
module Serializable
  def self.included(base)
    base.send(:include, InstanceMethods)
    base.prepend(Initializer)
  end

  module Initializer
    def initialize(attrs)
      attrs.each do |attr, value|
        self.send("#{attr}=", value)
      end
    end
  end

  module InstanceMethods
    def to_json
      to_h.to_json
    end

    def to_h
      instance_variables.each_with_object({}) do |var, hash|
        hash[var.to_s.delete("@")] = instance_variable_get(var)
      end
    end
  end
end
